version: 0.0
os: linux  # Amazon Linux, RHEL, Ubuntu Server일 경우 "linux", Windows Server일 경우 "windows"
files:
  - source: / # 인스턴스에 복사할 S3 파일의 경로, / 로 설정하면S3_BUCKET_NAME/PROJECT_NAME/GITHUB_SHA.zip
    destination: /home/ubuntu/pickrap-server/ # 프로젝트 이름  # S3에서 가져온 파일을 저장할 위치
    overwrite: yes # 덮어쓰기 허용

# files에서 가져온 파일들에게 권한을 어떻게 적용해야하는지 지정
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall: # LifeCycle Event Hook의 이름을 의미
    - location: scripts/execute.sh # 스크립트의 위치. files.destination에 정의한 경로에 대한 상대경로롤 작성
      timeout: 600 # 실행 타임아웃. 최대 3600초
      runas: ubuntu # 스크립트 실행 시 가장하는 사용자