version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: PickRapDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: vlzmfoq1!
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "3305:3306"
    networks:
      - db_network
    restart: always
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6378:6379"
    networks:
      - db_network
    restart: always

## deploy
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx-container
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx/web:/var/log/nginx/web
    command:
      "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - backbone

  green:
    build: .
    image: green
    container_name: green
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./:/home/ubuntu
      - /etc/localtime:/etc/localtime
    networks:
      - backbone

  blue:
    build: .
    container_name: blue
    restart: always
    ports:
      - "8082:8080"
    volumes:
      - ./:/home/ubuntu
      - /etc/localtime:/etc/localtime
    networks:
      - backbone

networks:
  db_network:
    driver: bridge
  backbone:
    driver: bridge

